### ISSUE TITLE
PDF build error

### ISSUE THREAD

**Issue by lorforlinux** [iSOLveIT/sphinx-pdf-generate-action#1]
@iSOLveIT Hey, thanks for creating this GitHub action. I am trying to use if for a project but getting this error. 

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v3, iSOLveIT/sphinx-pdf-generate-action@main. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by lorforlinux** [comment]
The above statement was just a warning that was resolved with updating `actions/setup-python@v3` to `actions/setup-python@master`.

Actual issue is with PDF Build,

```
  The HTML pages are in ../../../../../tmp/pages-79HULxBdMi.
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.8/x64/bin/sphinx-pdf-generate", line 8, in <module>
      sys.exit(main())
               ^^^^^^
    File "/opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/sphinx_pdf_generate/cli.py", line 124, in main
      raise PDFGenerateException(
  sphinx_pdf_generate.cli.PDFGenerateException: The The PDF metadata file, 'pdf_metadata.json', not found in the output directory. Check: /tmp/pages-79HULxBdMi
  Error: Invalid status code: 1
      at ChildProcess.<anonymous> (/home/runner/work/_actions/lorforlinux/sphinx-pdf-generate-action/main/main.js:9:19)
      at ChildProcess.emit (node:events:514:28)
      at maybeClose (node:internal/child_process:1105:16)
      at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
    code: 1
  }
  Error: Invalid status code: 1
      at ChildProcess.<anonymous> (/home/runner/work/_actions/lorforlinux/sphinx-pdf-generate-action/main/main.js:9:19)
      at ChildProcess.emit (node:events:514:28)
      at maybeClose (node:internal/child_process:1105:16)
      at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by iSOLveIT** [comment]
Hi @lorforlinux 
Thank you for reporting the issue. I will take a look into the problem and get back to you.
